language: python

python:
  - "3.7"

cache: pip

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  coverage run --source blackbox -m unittest discover tests

after_success:
  bash <(curl -s https://codecov.io/bash)