language: python

services:
  - docker

python:
  - "3.5"
  - "3.6"
  - "3.7"

cache: pip

before_install:
  - python --version
  - pip install --upgrade pip
  - docker build -t platinum/blackbox:0.0.1 .

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  coverage run --source blackbox -m unittest discover tests

after_success:
  bash <(curl -s https://codecov.io/bash)