language: python

services:
  - docker

env:
  global:
    - IMAGE_TAG=platinum/blackbox

python:
  - "3.5"
  - "3.6"
  - "3.7"

cache: pip

before_install:
  - python --version
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

jobs:
  include:
    - stage: "Python 3.5 Test"
      language: python
      python: 3.5
      script:
        python -m unittest discover tests
    - stage: "Python 3.6 Test"
      language: python
      python: 3.6
      script:
        python -m unittest discover tests
    - stage: "Python 3.7 Test & Coverage"
      language: python
      python: 3.7
      script:
        coverage run --source blackbox -m unittest discover tests
      after_success:
        bash <(curl -s https://codecov.io/bash)