language: python

cache: pip

before_install:
  - python --version
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

jobs:
  include:
    - stage: Python Tests
      name: Python 3.5 test
      language: python
      python: 3.5
      script: python -m unittest discover tests

    - language: python
      name: Python 3.6 test
      python: 3.6
      script: python -m unittest discover tests

    - language: python
      name: Python 3.7 test & coverage
      python: 3.7
      script: coverage run --source blackbox -m unittest discover tests
      after_success: bash <(curl -s https://codecov.io/bash)