language: python

services:
  - docker

cache: pip

before_install:
  - python --version
  - pip install --upgrade pip
  - docker build -t platinum/blackbox .

install:
  - pin install .
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

jobs:
  include:
    - stage: Python Lint
      script: flake8 blackbox/

    - stage: Python Tests
      language: python
      name: Python 3.6 test
      python: 3.6
      script: python -m unittest discover tests

    - language: python
      name: Python 3.7 test & coverage
      python: 3.7
      script: pytest
      after_success:
        - codecov