language: python

services:
  - docker
  - redis-server

cache: pip

before_install:
  - python --version
  - pip install --upgrade pip

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

jobs:
  include:
    - stage: Python Lint
      language: python
      name: Lint
      python: 3.7
      script: flake8 blackbox/

    - stage: Python Tests
      language: python
      name: Python 3.6 test
      python: 3.6
      script:
        - pytest

    - language: python
      name: Python 3.7 test & coverage
      python: 3.7
      script:
        - pytest
      after_success:
        - codecov -t $CODECOV_TOKEN

    - stage: Build Docker
      name: Build Docker
      script:
        - docker build -t platinum/blackbox .
