version: '3.7'

services:
  redis:
    image: 'redis:5.0.6-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    networks:
      - blackbox-net
    expose:
      - '6739'

  celery:
    build: .
    image: 'platinum/blackbox:0.0.1'
    depends_on:
      - redis
    command: celery -A blackbox.tasks.tasks worker -l info
    volumes:
      - 'models:/home/worker/blackbox'
    networks:
      - blackbox-net
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  blackbox:
    image: 'platinum/blackbox:0.0.1'
    depends_on:
      - celery
    ports:
      - '5678:5678'
    volumes:
      - 'models:/home/worker/blackbox'
    networks:
      - blackbox-net
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  redis:
  models:

networks:
  blackbox-net:

