version: '3.7'

services:
  redis:
    image: 'redis:5.0.6-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    networks:
      - blackbox-net
    expose:
      - '6739'

  celery:
    build: .
    image: 'platinum/blackbox:0.2.0'
    depends_on:
      - redis
    command: celery -A blackbox.tasks.tasks worker -l info
    volumes:
      - 'models:/home/worker/blackbox'
    networks:
      - blackbox-net
      - orion-net
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ORION_CONTEXT_BROKER=http://orion:1026

  blackbox:
    image: 'platinum/blackbox:0.2.0'
    depends_on:
      - celery
    ports:
      - '5678:5678'
    volumes:
      - 'models:/home/worker/blackbox'
    networks:
      - blackbox-net
      - orion-net
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ORION_CONTEXT_BROKER=http://orion:1026

  mongo:
    image: mongo:3.6
    command: --nojournal
    expose:
      - '27017'
    volumes:
      - mongo:/data
    networks:
      - orion-net

  orion:
    image: fiware/orion
    depends_on:
      - mongo
    expose:
      - '1026'
    ports:
      - '1026:1026'
    networks:
      - orion-net
    command: -dbhost mongo -logLevel DEBUG

volumes:
  redis:
  models:
  mongo:

networks:
  blackbox-net:
  orion-net:

